In [2]:
import numpy as np

In [3]:
inputs = [2,4,7]
weights = [0.3, 0.5, -0.2]
bias = 2

output = np.dot(inputs, weights) + bias
print(output)

3.2


In [11]:
input = weights = list(range(1,11))

print(input)
print(weights)

bias = 10
output = 0

for i in range(len(input)):
    output += input[i] * weights[i]

print(output + bias)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
395


In [47]:
inputs = np.random.randint(0, 10, 3)
weights = np.random.random(3)
bias = 10

print (inputs)
print(weights)

output = np.dot(inputs, weights) + bias
print(output)

[3 0 0]
[0.20045141 0.87791345 0.08454789]
10.601354231660194


In [73]:
inputs = [1,2,3]
weights = np.array([
    [0.2, 0.8, -0.5], 
    [0.5, -0.91, 0.26], 
    [-0.26, -0.27, 0.17],
    [0.87, 0.03, 0.8]
    ])

print(weights.shape)

bias = [2, 3, 0.5, 1]

output1 = inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + bias[0]
output2 = inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + bias[1]
output3 = inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + bias[2]
output4 = inputs[0] * weights[3][0] + inputs[1] * weights[3][1] + inputs[2] * weights[3][2] + bias[3]
# output1 = np.dot(inputs, weights[0]) + bias[0]
print(output1)
print(output2)
print(output3)
print(output4)

# output = np.dot(inputs, np.array(weights).T) + bias
output = np.dot(weights,inputs) + bias
print(output)

(4, 3)
2.3
2.46
0.20999999999999996
4.33
[2.3  2.46 0.21 4.33]


In [118]:
inputs = np.random.randint(0, 10, 3)
print(inputs.shape)

weights1 = np.random.random((4, len(inputs)))

print(weights.shape)

bias1 = np.random.random(4)

output1 = np.dot(inputs, weights1.T) + bias1

print(output1)

output1.shape

input2 = output1

weights2 = np.random.random((3, 4))
biases2 = np.random.random(3)

output2 = np.dot(input2, weights2.T) + biases2
print(output2)


(3,)
(4, 3)
[2.7388538  3.25413856 0.73546074 5.38740812]
[8.61466412 7.63501806 9.2685499 ]


In [143]:
class Layer:
    def __init__(self, n_inputs, n_neurons):
        self.weights = np.random.random(( n_neurons, n_inputs ))
        self.biases = np.random.random(n_neurons)
    
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights.T) + self.biases


inputs = np.random.randint(0, 10, 3)
layer1 = Layer(3, 4)
layer1.forward(inputs)
print(layer1.output.shape)


layer2 = Layer(4, 3)
layer2.forward(layer1.output)
print(layer2.output.shape)

(4,)
(3,)
