In [2]:
import numpy as np

In [3]:
inputs = [2,4,7]
weights = [0.3, 0.5, -0.2]
bias = 2

output = np.dot(inputs, weights) + bias
print(output)

3.2


In [11]:
input = weights = list(range(1,11))

print(input)
print(weights)

bias = 10
output = 0

for i in range(len(input)):
    output += input[i] * weights[i]

print(output + bias)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
395


In [47]:
inputs = np.random.randint(0, 10, 3)
weights = np.random.random(3)
bias = 10

print (inputs)
print(weights)

output = np.dot(inputs, weights) + bias
print(output)

[3 0 0]
[0.20045141 0.87791345 0.08454789]
10.601354231660194


In [73]:
inputs = [1,2,3]
weights = np.array([
    [0.2, 0.8, -0.5], 
    [0.5, -0.91, 0.26], 
    [-0.26, -0.27, 0.17],
    [0.87, 0.03, 0.8]
    ])

print(weights.shape)

bias = [2, 3, 0.5, 1]

output1 = inputs[0] * weights[0][0] + inputs[1] * weights[0][1] + inputs[2] * weights[0][2] + bias[0]
output2 = inputs[0] * weights[1][0] + inputs[1] * weights[1][1] + inputs[2] * weights[1][2] + bias[1]
output3 = inputs[0] * weights[2][0] + inputs[1] * weights[2][1] + inputs[2] * weights[2][2] + bias[2]
output4 = inputs[0] * weights[3][0] + inputs[1] * weights[3][1] + inputs[2] * weights[3][2] + bias[3]
# output1 = np.dot(inputs, weights[0]) + bias[0]
print(output1)
print(output2)
print(output3)
print(output4)

# output = np.dot(inputs, np.array(weights).T) + bias
output = np.dot(weights,inputs) + bias
print(output)

(4, 3)
2.3
2.46
0.20999999999999996
4.33
[2.3  2.46 0.21 4.33]


In [107]:
inputs = np.random.randint(0, 10, 3)
print(inputs.shape)

weights = np.random.random((4, len(inputs)))

print(weights.shape)

bias = np.random.random(4)

output = np.dot(inputs, weights.T) + bias

print(output)


(3,)
(4, 3)
[5.77054453 8.41481409 8.64154866 7.27949036]
